### ISSUE TITLE
GPLv3 license is incompatible with App Store

### ISSUE THREAD

**Issue by ex-nerd** [Glucosio/glucosio-ios#20]
This is more an FYI than a bug report.

See: http://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement

Basically, software distributed exclusively via a GPLv3 license (as this app appears to be) will be rejected from the App Store because the GPL does not allow additional restrictions to be added by downstream providers (which the App Store does).

Knowing how difficult it is to re-license (or even add a second license to) an existing GPL project, I felt it was worth mentioning before you get too many contributors (who may not read your CLA closely enough, and complain later if you switch away from the GPL).

P.S.  You have a random `(` at the start of the second paragraph of section 2.3 in your CLA.

**Comment by ghost** [comment]
We've consulted Software Freedom Law Center, an licensing expert at Mozilla and VLC on this topic and the feedback we got as that through a CLA we can restrict disputes to distribution through the App Store.

Simply put Apple has no issue with the GPLv3 but on the request of a copyright holder would be obligated to respond to a DMCA which happened in the case of Gnu GO and VLC for Mobile.

That said when making a commit as a pre-condition for the project accepting the contribution and it then being licensed GPLv3 the contributor waives their right to dispute distribution per section 2.1(C) of our CLA which is an agreement the contributor makes with the project.

That said it is our understanding that having that signed CLA in hand would be a solid defense to any contributor who would try to exercise those rights because as a pre-condition in a contract they have waived their right to exercise them against the project.

I don't particularly like us having to do it this way but unfortunately in order to license under the GPL this was the suggestion we got.

We'd prefer not to relicense as we like the GPLv3 in all aspects but want to ensure the ability to be able to distribute in that specific channel without dispute and having a solid defense in hand.

If you still think this is a valid bug given the explanation I've provided please comment again and I can ask for further review from SFLC and also reach out to the FSF (that said they the FSF do know about the project and actually invited us to LibrePlanet this year)

**Comment by ex-nerd** [comment]
Great to hear that you got help from the SFLC (they're such a great resource to have).  It would be nice if the FSF were to put out an updated post about this but it's probably not in line with their specific agenda (if you ever mention Apple to RMS, he is _very_ clear how he feels about them in general).

And I wasn't really referring to legal defense (your CLA seems good) but more just warning of possible future PR problems.  Some F/LOSS devs can be noisy nitpickers but hopefully your comment here is enough to assuage any future concerns/questions on the subject.

**Comment by ghost** [comment]
That said I'll close this but thanks for opening this because it would be good to point to in the future. We only have the best intentions in mind and wish we didn't need a CLA and wouldn't have one if it were not for this one issue.
